# Generated by Django 4.0.6 on 2022-07-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0003_team_alter_feedback_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
