# Generated by Django 4.0.6 on 2022-07-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0005_feedback_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
