# Generated by Django 4.0.6 on 2022-07-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0006_rename_team_name_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partner_logo/%y'),
        ),
    ]
