# Generated by Django 4.0.6 on 2022-07-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0007_alter_partner_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
