# Generated by Django 4.0.6 on 2022-07-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0009_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
