# Generated by Django 4.0.6 on 2022-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0010_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_profile', models.ImageField(upload_to='feedback_profile/%y')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('statement', models.TextField()),
            ],
        ),
    ]
