# Generated by Django 4.0.6 on 2022-07-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0012_ojtteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OjtTeam',
        ),
    ]
