# Generated by Django 4.0.6 on 2022-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastlane', '0013_delete_ojtteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='OjtTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('ojtprofile', models.ImageField(upload_to='ojt_profile/%y')),
            ],
        ),
    ]
